name: Gitter release notification
on: create

jobs:
  notify:
    if: github.ref_type == 'tag'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: curl --data-urlencode "message=[${{github.repository}} ${{github.ref_name}}](https://github.com/${{github.repository}}/releases/${{github.ref_name}}) released" ${{secrets.GITTER_CUSTOM_WEBHOOK}}
